# Generated by Django 5.0.6 on 2024-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("key", models.TextField(unique=True)),
                ("value", models.TextField(default="")),
            ],
        ),
    ]
